variable "cluster_arn" {}
variable "task_definition_arn" {}
variable "subnet_id" {}
variable "vpc_id" {}
variable "region" {}
variable "account_id" {}
variable "task_role_arn" {}
variable "task_execution_role_arn" {}
variable "num_machine" {}
