variable "cluster_arn" {}
variable "task_definition_arn" {}
variable "subnet_id" {}
variable "security_group_id" {}
variable "region" {}
variable "account_id" {}
variable "task_role_arn" {}
variable "task_execution_role_arn" {}
variable "num_machine" {}
variable "default_pdf_name" {}
variable "default_bucket_name" {}
