name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}
    steps:
    - uses: actions/checkout@v4
    - name: Install AWS CLI
      run: |
        if command -v aws &> /dev/null; then
          echo "AWS CLI is already installed. Updating..."
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
        else
          echo "Installing AWS CLI..."
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
        fi
    - name: save timestamp
      id: time_stamp
      run: echo "time_stamp=$(date +%s)" >> $GITHUB_ENV
    - name: Build the Docker image
      id: build
      run: |
        docker build ./code/split_pdf_go --file ./code/split_pdf_go/Dockerfile --tag ${{ secrets.ECR_REPOSITORY_NAME }}:${{ env.time_stamp }} --platform linux/amd64
        echo "::set-output name=image_tag::${{ secrets.ECR_REPOSITORY_NAME }}:${{ env.time_stamp }}"
    - name: login to docker hub
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com
    - name: add tag to docker image
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        time_stamp: ${{ env.time_stamp }}
      run: docker tag  ${{ secrets.ECR_REPOSITORY_NAME }}:${{ env.time_stamp }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:${{ env.time_stamp }}
    - name: push docker image
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        time_stamp: ${{ env.time_stamp }}
      run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/${{ env.ECR_REPOSITORY_NAME }}:${{ env.time_stamp }}